# Generated by Django 5.0.1 on 2024-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_candidate_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=120)),
                ('voter_id', models.CharField(max_length=120)),
                ('voter_address', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
