# Generated by Django 5.0.1 on 2024-07-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_remove_voter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='vote_casted',
            field=models.BooleanField(default=False),
        ),
    ]
